services:
  ffmpeg-builder:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ANDROID_NDK_VERSION: r27d
    image: javiermk/vidra-ffmpeg:latest
    volumes:
      - ./dist:/dist
      - ./config.sh:/config.sh:ro
      - ./compile.sh:/compile.sh:ro
      - ./docker-builder:/docker-builder:ro
    entrypoint: ["/compile.sh"]