services:
  ffmpeg-builder:
    build:
      context: .

    image: javiermk/vidra-ffmpeg:latest
    container_name: vidra-ffmpeg-builder
    volumes:
      - ./dist:/dist
      - ./temp/sources:/source
      - ./config.sh:/config.sh:ro
      - ./compile.sh:/compile.sh:ro
    entrypoint: ["bash", "/compile.sh"]